name: AKS Full CI/CD (Build -> Push -> Deploy)

on:
  push:
    branches: ["master"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name acedevopsdemoacr

      - name: Build image
        run: docker build -t acedevopsdemoacr.azurecr.io/devops:latest .

      - name: Push image
        run: docker push acedevopsdemoacr.azurecr.io/devops:latest

      - name: Get AKS credentials
        run: az aks get-credentials -g chainsure -n devops-aks --overwrite-existing

      - name: Apply manifests (first time safe)
        run: kubectl apply -f k8s/

      - name: Rollout restart (force new image)
        run: |
          kubectl rollout restart deployment/devops-app
          kubectl rollout status deployment/devops-app
